### ISSUE TITLE
startxfce4_termux.sh throws error

### ISSUE THREAD

**Issue by defencedog** [LinuxDroidMaster/Termux-Desktops#34]
```
~ $ neofetch
         -o          o-            u0_a636@localhost                                                                                                           +hydNNNNdyh+             -----------------
        +mMMMMMMMMMMMMm+           OS: Android 13 aarch64
      `dMMm:NMMMMMMN:mMMd`         Host: samsung SM-T870                                                                                                   hMMMMMMMMMMMMMMMMMMh         Kernel: 4.19.113-27114284
  ..  yyyyyyyyyyyyyyyyyyyy  ..     Uptime: 36 days, 3 hours, 12 mins
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.   Packages: 369 (dpkg), 1 (pkg)                                                                                     :MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Shell: bash 5.2.26
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   CPU: Qualcomm KONA (8) @ 1.804GHz
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Memory: 5323MiB / 7643MiB                                                                                         :MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+                                                                                                                            mMMMMMMMMMMMMMMMMMMm
      `/++MMMMh++hMMMM++/`
          MMMMo  oMMMM                                                                                                                                         MMMMo  oMMMM
          oNMm-  -mMNs
                                                                                                                                                     ~ $
```

Above is my system info. I followed instruction of this video https://www.youtube.com/watch?v=rq85dxMb7e4

```
~ $ ./startxfce4_termux.sh
java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:536)
        at com.termux.x11.Loader.main(Loader.java:25)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:411)
Caused by: java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
        ... 5 more
~ $ xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
```

**Comment by ihtarlik** [comment]
The error mentioned here is an error launching the Termux X11 app. Remove it and install the latest nightly build for your system from here:

[https://github.com/termux/termux-x11/releases](https://github.com/termux/termux-x11/releases)
