### ISSUE TITLE
Debian on chroot breaks android temporarily

### ISSUE THREAD

**Issue by spidermodders** [LinuxDroidMaster/Termux-Desktops#59]
For whatever reason, it does not seem save to install Debian on the tmp directory especially if the device is running android 14 and up.

I am on s23 Ultra by the way, rooted with magisk and twrp, masked with kitsunemask

Here are a bunch of issues that come up:
**Unable to start xfce 4:**
When starting xfce4 after the installation outside root, I get hit with this error:
```
Xwayland: no process found
virgl_test_server_android: no process found
termux-wake-lock: no process found
Starting: Intent { cmp=com.termux.x11/.MainActivity }
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:149)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
        at java.net.ServerSocket.bind(ServerSocket.java:399)
        at java.net.ServerSocket.<init>(ServerSocket.java:259)
        at com.termux.x11.CmdEntryPoint.lambda$spawnListeningThread$1(CmdEntryPoint.java:144)
        at com.termux.x11.CmdEntryPoint.$r8$lambda$ViPcpFnEzoJCKyl-YNiduQ0Vo1o(CmdEntryPoint.java:0)
        at com.termux.x11.CmdEntryPoint$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:138)
        at libcore.io.IoBridge.bind(IoBridge.java:145)
        ... 8 more
mkdir: '/data/local/tmp/chrootDebian/dev/shm': File exists
mkdir: '/data/local/tmp/chrootDebian/sdcard': File exists
dbus-daemon[11919]: Failed to start message bus: Failed to bind socket "/tmp/dbus-CZrcaGvMQs": Permission denied
EOF in dbus-launch reading address from bus daemon
```
Interestingly, after that my entire device starts tweaking. 

**What happens after the error:**
After that I am unable to open up multiple apps, these include:
Galaxy store,
Discord,
Playstore,
Magisk, 
Basically any app which includes in build webui stuff or something like that.
After restarting my phone the issues no longer persists BUT:
**After restarting my phone, it entered a soft sleep mode for around 3 minutes until it finally boots up again...**
I suspect the reason for this is, android tries to remove the tmp files, and because of that nature it goes through each single file in serial making the removing process very slow. After my phone boots up again, everything seems normal and the files inside /tmp persist. Why? Android failed to remove them. Why? I don't know but the permission seem locked for any File inside the Debian chroot folder (which is inside the tmp folder). **I even tried the following commands:**
**chown -R root:root /tmp
chmod -R 1777 /tmp**
**But got hit with a "Not permitted error" for every single file (in serial)**

Please take a look at this @LinuxDroidMaster and consider changing the files directory to another root folder is possible.

**Comment by katokii0** [comment]
> For whatever reason, it does not seem save to install Debian on the tmp directory especially if the device is running android 14 and up.
> 
> 
> 
> I am on s23 Ultra by the way, rooted with magisk and twrp, masked with kitsunemask
> 
> 
> 
> Here are a bunch of issues that come up:
> 
> **Unable to start xfce 4:**
> 
> When starting xfce4 after the installation outside root, I get hit with this error:
> 
> ```
> 
> Xwayland: no process found
> 
> virgl_test_server_android: no process found
> 
> termux-wake-lock: no process found
> 
> Starting: Intent { cmp=com.termux.x11/.MainActivity }
> 
> _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
> 
> java.net.BindException: bind failed: EADDRINUSE (Address already in use)
> 
>         at libcore.io.IoBridge.bind(IoBridge.java:149)
> 
>         at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
> 
>         at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
> 
>         at java.net.ServerSocket.bind(ServerSocket.java:399)
> 
>         at java.net.ServerSocket.<init>(ServerSocket.java:259)
> 
>         at com.termux.x11.CmdEntryPoint.lambda$spawnListeningThread$1(CmdEntryPoint.java:144)
> 
>         at com.termux.x11.CmdEntryPoint.$r8$lambda$ViPcpFnEzoJCKyl-YNiduQ0Vo1o(CmdEntryPoint.java:0)
> 
>         at com.termux.x11.CmdEntryPoint$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
> 
>         at java.lang.Thread.run(Thread.java:1012)
> 
> Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
> 
>         at libcore.io.Linux.bind(Native Method)
> 
>         at libcore.io.ForwardingOs.bind(ForwardingOs.java:138)
> 
>         at libcore.io.IoBridge.bind(IoBridge.java:145)
> 
>         ... 8 more
> 
> mkdir: '/data/local/tmp/chrootDebian/dev/shm': File exists
> 
> mkdir: '/data/local/tmp/chrootDebian/sdcard': File exists
> 
> dbus-daemon[11919]: Failed to start message bus: Failed to bind socket "/tmp/dbus-CZrcaGvMQs": Permission denied
> 
> EOF in dbus-launch reading address from bus daemon
> 
> ```
> 
> Interestingly, after that my entire device starts tweaking. 
> 
> 
> 
> **What happens after the error:**
> 
> After that I am unable to open up multiple apps, these include:
> 
> Galaxy store,
> 
> Discord,
> 
> Playstore,
> 
> Magisk, 
> 
> Basically any app which includes in build webui stuff or something like that.
> 
> After restarting my phone the issues no longer persists BUT:
> 
> **After restarting my phone, it entered a soft sleep mode for around 3 minutes until it finally boots up again...**
> 
> I suspect the reason for this is, android tries to remove the tmp files, and because of that nature it goes through each single file in serial making the removing process very slow. After my phone boots up again, everything seems normal and the files inside /tmp persist. Why? Android failed to remove them. Why? I don't know but the permission seem locked for any File inside the Debian chroot folder (which is inside the tmp folder). **I even tried the following commands:**
> 
> **chown -R root:root /tmp
> 
> chmod -R 1777 /tmp**
> 
> **But got hit with a "Not permitted error" for every single file (in serial)**
> 
> 
> 
> Please take a look at this @LinuxDroidMaster and consider changing the files directory to another root folder is possible. 

Hi did u find a way to fix the problem ?

**Comment by spidermodders** [comment]
> 
> Hi did u find a way to fix the problem ?

Yes I figured out that I should leave the tmp folder un touched and edited the entire source Code to install it to data/anycustompath because for me my device goes crazy if there are permission locked files inside the tmp folder. Unfortunately the fix is very complicated and explaining each step on how to do this would be a pain in the ass. However I may make a tutorial Video on that sometime
